"""Sample-corpus generation for the Aurora Mobile RAG pipeline (LLM + PDF).

Generates realistic policy documents (policies, processes, eligibility terms,
terms & conditions) for the Aurora Mobile telecom retail domain. Each
document's canonical metadata (title, Document ID, version, last-updated date,
department) is curated inline. The body text is generated by an LLM through
OpenRouter and rendered into a branded PDF.

The chat model is read from the pipeline configuration (``rag.config.Settings``,
which loads ``OPENROUTER_MODEL`` from the environment or ``.env``). The embedding
model is irrelevant here; this script only needs the generation model and the
OpenRouter API key.

Some documents are flagged as long and are generated section-by-section so
their rendered PDFs exceed 10 pages; the rest are generated in a single pass.

Output is written under data/raw/ (the pipeline's ``data_dir``), one
subdirectory per category, so the RAG indexer discovers them recursively:

    data/raw/
    ├── billing/
    │   ├── billing-dispute-policy.pdf
    │   ├── refund-policy.pdf
    │   ├── payment-policy.pdf
    │   ├── billing_invoice_policy.pdf
    │   ├── payment_eligibility_terms.pdf
    │   └── returns_refunds_policy.pdf
    ├── mobile/
    │   ├── mobile-contract-policy.pdf
    │   ├── sim-replacement-policy.pdf
    │   ├── number-portability-policy.pdf
    │   ├── postpaid_plan_guidelines.pdf
    │   ├── plan_upgrade_policy.pdf
    │   ├── data_plan_terms_conditions.pdf
    │   ├── device_upgrade_guidelines.pdf
    │   ├── device_trade_in_process.pdf
    │   └── device_protection_policy.pdf
    ├── roaming/
    │   ├── roaming-policy.pdf
    │   ├── international-roaming-policy.pdf
    │   └── international_roaming_policy.pdf
    ├── customer/
    │   ├── customer-verification-policy.pdf
    │   ├── complaint-handling-policy.pdf
    │   ├── new_line_activation_process.pdf
    │   ├── port_in_policy.pdf
    │   ├── promotions_eligibility_terms.pdf
    │   └── loyalty_rewards_program.pdf
    └── compliance/
        ├── kyc-policy.pdf
        ├── data-privacy-policy.pdf
        ├── privacy_data_protection_policy.pdf
        └── network_service_level_agreement.pdf

Usage:
    python scripts/generate_sample_pdfs.py                 # all documents
    python scripts/generate_sample_pdfs.py --limit 4       # first N documents
    python scripts/generate_sample_pdfs.py --only roaming  # documents matching name
    python scripts/generate_sample_pdfs.py --keep-md       # also save raw markdown

Requires OPENROUTER_MODEL and OPENROUTER_API_KEY in the environment or .env.
"""

import argparse
import logging
import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from openai import OpenAI

from rag.config import Settings

logger = logging.getLogger(__name__)

try:
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        HRFlowable,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )
except ImportError as exc:  # pragma: no cover - environment check
    raise SystemExit(
        "Missing dependency for PDF rendering. Install with:\n    uv add reportlab"
    ) from exc


# =============================================================================
# 0. OUTPUT PATH
# =============================================================================

ROOT = Path(__file__).resolve().parent.parent

DEFAULT_OUTPUT_DIR = ROOT / "data" / "raw"

# The generation model comes from rag.config.Settings (OPENROUTER_MODEL in the
# environment or .env), the same configuration the RAG pipeline uses.
MAX_COMPLETION_TOKENS_TO_WARN = 4096
LONG_DOC_SECTIONS = 15  # >10 pages when fully written
SECTION_BATCH = 3  # sections generated per LLM call
BODY_MAX_TOKENS = 4096  # default bound so a bare call doesn't reserve the full output budget
OUTLINE_MAX_TOKENS = 1200
SECTION_MAX_TOKENS = 3000
FAQ_MAX_TOKENS = 2000


# =============================================================================
# 1. KNOWLEDGE DOCUMENT SCHEMA
# =============================================================================


@dataclass
class KnowledgeMetadata:
    title: str
    doc_id: str
    version: str
    last_updated: str
    department: str
    category: str
    brief: str
    sections: int = 0  # 0 -> single-pass generation (a few pages)


@dataclass
class KnowledgeDocument:
    metadata: KnowledgeMetadata
    body_md: str


# =============================================================================
# 2. CURATED DOCUMENT CATALOG (canonical metadata + generation briefs)
#     Company: Aurora Mobile
# =============================================================================

KB: dict[str, KnowledgeMetadata] = {
    # -------------------------------------------------------------------------
    # billing/  (Finance Operations)
    # -------------------------------------------------------------------------
    "billing-dispute-policy": KnowledgeMetadata(
        title="Billing Dispute Policy",
        doc_id="AUR-BIL-010",
        version="2.0",
        last_updated="August 2026",
        department="Finance Operations",
        category="billing",
        brief=(
            "How customers contest invoice charges. Cover: 60-day filing window "
            "from invoice date, required information (invoice number, disputed "
            "amount, reason), filing channels (app, portal, phone, in-store), "
            "investigation SLA (5 business days), credit issued within 5 "
            "business days for validated errors, disputed amounts held during "
            "review so no late fees accrue, case number + estimated resolution "
            "timeline given to customer, escalation to CFPB/state regulator "
            "after 30 days unresolved, duplicate-dispute rules, and FAQs."
        ),
    ),
    "refund-policy": KnowledgeMetadata(
        title="Refund Policy",
        doc_id="AUR-BIL-011",
        version="2.1",
        last_updated="July 2026",
        department="Finance Operations",
        category="billing",
        brief=(
            "Refunds for canceled lines and returned devices. Cover: 14-day "
            "cooling-off window for new lines, refund to original payment "
            "method within 7-10 business days, activation fee refunded when the "
            "full line is canceled in-window, prorated plan charges deducted "
            "for days used, device installment payments refunded, promotional "
            "credits clawed back, restocking fee $35 (waived for DOA/dead-on-"
            "arrival within 14 days), refund on financed account lines, gift "
            "cards / prepaid airtime not refundable, and FAQs."
        ),
    ),
    "payment-policy": KnowledgeMetadata(
        title="Payment Policy",
        doc_id="AUR-BIL-012",
        version="2.0",
        last_updated="June 2026",
        department="Finance Operations",
        category="billing",
        brief=(
            "Accepted payments and payment plans. Cover: payment methods table "
            "(credit/debit instant, ACH 3-5 business days, digital wallet "
            "instant, in-store cash/card instant, mailed check 7-10 days) with "
            "note that prepaid cards are one-time only, autopay (enabled by "
            "default, $5/mo discount on Premium/Unlimited/Business plans, 2 "
            "retries over 5 business days, $5 retry fee after failures), 15-day "
            "due window, installment payment plans (Active account, 12+ months "
            "tenure, minimum balance $100, max 3 monthly installments, 0% on "
            "first plan then 5%, once per 6 months, balances over $500 require "
            "manager approval), late fees ($10 late payment, $25 returned "
            "payment, $35 chargeback), refundable deposits $100-$500 for new "
            "customers (refunded after 12 months of on-time payments), and FAQs."
        ),
    ),
    "billing_invoice_policy": KnowledgeMetadata(
        title="Billing & Invoice Policy",
        doc_id="AUR-BIL-001",
        version="2.1",
        last_updated="August 2026",
        department="Finance Operations",
        category="billing",
        brief=(
            "Monthly invoicing rules. Cover: invoice cycle (15-day due window), "
            "invoice line items (plan charge, taxes/fees ~8-12%, add-ons, "
            "device installments, protection, service fees, promo credits), "
            "autopay (enabled by default, $5/mo discount on Premium/Unlimited/"
            "Business, 2 retries over 5 business days, $5 retry fee), account "
            "status ladder (Active / Past Due 15-30d / Delinquent >30d / "
            "Suspended 45d / Prospect / Closed 90d to collections), late fees "
            "table ($10 late, $25 returned payment, $35 chargeback, $2 paper "
            "invoice), automated bill optimization reviews (usage <60% for 2 "
            "cycles recommends downgrade, family consolidation, autopay "
            "enrollment, add-on cleanup), disputes (60-day window, credit in "
            "5 business days, amounts held during review, case number), 10% "
            "discount for annual prepayment, and FAQs."
        ),
    ),
    "payment_eligibility_terms": KnowledgeMetadata(
        title="Payment & Eligibility Terms",
        doc_id="AUR-BIL-002",
        version="2.0",
        last_updated="June 2026",
        department="Finance Operations",
        category="billing",
        brief=(
            "Payment methods and eligibility. Cover: accepted payment methods "
            "table (credit/debit card, ACH 3-5 day settlement, in-store cash/"
            "card instant, digital wallet instant, mailed check 7-10 days), "
            "method requirements (funding account must belong to account "
            "holder, prepaid cards one-time only, no autopay with prepaid), "
            "payment plan installments (Active account, 12+ months tenure, min "
            "balance $100, max 3 monthly installments, 0% first plan then 5%, "
            "once per 6 months, $500+ needs manager approval, no plan defaults "
            "in last 12 months), credit check requirements (soft pull BYOD, "
            "hard pull financed with device, none for prepaid), prepaid "
            "deposits $100-$500 refundable after 12 months, disputes (60-day "
            "window, 5-day investigation, CFPB escalation), autopay and "
            "reminder schedule (3 days before, past-due notices on days "
            "7/15/30/45), and FAQs."
        ),
    ),
    "returns_refunds_policy": KnowledgeMetadata(
        title="Returns & Refunds Policy",
        doc_id="AUR-SRV-003",
        version="3.2",
        last_updated="August 2026",
        department="Retail Operations",
        category="billing",
        brief=(
            "Cooling-off returns and refunds. Cover: return windows table "
            "(new device 14 days $35 restocking fee waived for DOA, eSIM-only "
            "14 days no fee, open-box/refurbished 7 days $35, accessory "
            "unopened 30 days, opened 14 days), refund mechanics (7-10 business "
            "days to original payment method, activation fee refunded with full "
            "line cancellation, used days deducted, device installments "
            "refunded, promo credits clawed back), acceptable device condition "
            "(original packaging, no cracks, no liquid damage indicators, "
            "activation lock removed, factory reset), condition assessment "
            "table (like new full refund, cosmetic wear $35 restocking fee, "
            "screen crack 50% refund + $35, liquid damage no refund, missing "
            "accessories deducted), DOA handling (14 days, replacement next "
            "business day, free return shipping, refund option), online/mail "
            "returns ($10 from refund for change of mind, postmark within "
            "window), non-returnable items (gift cards, prepaid airtime, "
            "activated digital content, lost/stolen devices, third-party "
            "repaired devices), and FAQs."
        ),
    ),
    # -------------------------------------------------------------------------
    # mobile/  (Mobile Services / Carrier Services / Consumer Plans / Legal)
    # -------------------------------------------------------------------------
    "mobile-contract-policy": KnowledgeMetadata(
        title="Mobile Contract Policy",
        doc_id="AUR-MOB-001",
        version="3.0",
        last_updated="August 2026",
        department="Legal & Compliance",
        category="mobile",
        sections=LONG_DOC_SECTIONS,
        brief=(
            "Terms governing monthly mobile service contracts. Cover: month-to-"
            "month auto-renewing service term, 14-day cooling-off period, early "
            "termination fee ($175) when a line on a promotional device "
            "contract is canceled before 12 months, device installment "
            "agreements are separate and always payable in full on "
            "cancellation, 30-day notice for material contract changes, "
            "customer right to terminate without penalty upon material "
            "changes, fair use / network management clauses, prohibited uses "
            "(reselling, automated messaging, illegal content), liability and "
            "service limitation disclaimers, binding arbitration clause with a "
            "small-claims exception, billing and payment integration, and FAQs."
        ),
    ),
    "sim-replacement-policy": KnowledgeMetadata(
        title="SIM Replacement Policy",
        doc_id="AUR-MOB-002",
        version="1.4",
        last_updated="July 2026",
        department="Mobile Services",
        category="mobile",
        brief=(
            "Issue new physical SIM or eSIM for existing lines. Cover: when a "
            "replacement is needed (lost/stolen/damaged SIM, new device, "
            "upgrade to eSIM), free replacement within 14 days of activation "
            "then $10 fee, in-store replacement in 10 minutes or shipped in 2 "
            "business days, eSIM re-issued via app or email within minutes, "
            "compatible eSIM devices (iPhone XS+, Galaxy S20+, Pixel 3+), "
            "identity verification (two-factor: IMEI + government ID) before "
            "issuing, lost/stolen SIM blocked via 24/7 hotline, number and "
            "plan unchanged, dual-SIM on compatible devices, and FAQs."
        ),
    ),
    "number-portability-policy": KnowledgeMetadata(
        title="Number Portability Policy",
        doc_id="AUR-MOB-003",
        version="2.5",
        last_updated="August 2026",
        department="Carrier Services",
        category="mobile",
        brief=(
            "Porting an existing number from another carrier. Cover: "
            "eligibility (active number in good standing, TPIN + account "
            "number required, not mid-port or suspended), required information "
            "table (phone number, losing-carrier account number, transfer PIN, "
            "exact name and address match), timelines (same region 2-4 hours, "
            "cross-region 24-48 hours, corporate 3-5 business days, prepaid-"
            "to-postpaid 24-48 hours, US numbers only), common failure reasons "
            "and resolutions table (wrong TPIN, name/address mismatch, "
            "suspended line, pending device balance, already mid-port, losing "
            "carrier blocking), step-by-step port process, zero-day trouble "
            "escalation through the Port Desk with 24-hour resolution, partial "
            "port line-by-line, and FAQs."
        ),
    ),
    "postpaid_plan_guidelines": KnowledgeMetadata(
        title="Postpaid Plan Guidelines",
        doc_id="AUR-PLN-001",
        version="3.0",
        last_updated="August 2026",
        department="Consumer Plans",
        category="mobile",
        sections=LONG_DOC_SECTIONS,
        brief=(
            (
                "Detailed postpaid plan catalog. Cover: plan categories (Essential "
                "5GB/500min/500SMS $40, Standard 20GB/1000/1000 $60, Premium 50GB/"
                "unlimited $80, Family 100GB shared $120 for 2 lines +$30/line, "
                "Unlimited $90, Business 200GB pooled per 5 lines $200 +$40/line, "
                "Senior 65+ 10GB $30), data allowance/overage behavior table "
                "(throttle to 128kbps Essential/Senior, 256kbps Standard/Family, "
                "512kbps Premium, 1Mbps Business, deprioritize Unlimited)"
            ),
            (
                "features matrix (talk, text, hotspot, intl. calling, Wi-Fi "
                "calling, priority network, voicemail, call forwarding, spam "
                "blocking), change policies (downgrade next cycle, upgrade "
                "immediate with proration, 14-day cooling-off, no effect on device "
                "installments), promotional pricing (per-account, max 2 "
                "discounts, 30-day expiry notice), data sharing add-on $10/month, "
                "FAQ on travel add-on $15/day, and FAQs."
            ),
        ),
    ),
    "plan_upgrade_policy": KnowledgeMetadata(
        title="Plan Upgrade Policy",
        doc_id="AUR-PLN-002",
        version="2.0",
        last_updated="July 2026",
        department="Consumer Plans",
        category="mobile",
        brief=(
            "When and how a customer may upgrade to a higher-tier plan. Cover: "
            "eligibility criteria (Active status, current plan 30+ days, no "
            "arrears, no device installment arrears, KYC within 12 months, no "
            "fraud/abuse flag), account-status eligibility table (Active yes / "
            "Prospect needs activation / Delinquent no / Suspended no), "
            "available upgrade paths per current plan table (Essential to "
            "Standard/Premium/Family, Standard to Premium/Family/Unlimited, "
            "Premium to Unlimited/Family/Business, Family to Unlimited/Business, "
            "Senior to Essential/Standard/Premium with 60-day tenure), "
            "step-by-step upgrade process (7 steps with 60-day usage analysis), "
            "proration formula (new_price-old_price)*days_remaining/"
            "days_in_cycle, immediate effective date, device installments "
            "unaffected), promotional pricing (stacking rules, 30-day opt-out), "
            "usage-based auto recommendations (downgrade candidates <40% for 3 "
            "months, upgrade candidates >80% for 2 months, SMS at cycle "
            "start), 24-hour reversal window, and FAQs."
        ),
    ),
    "data_plan_terms_conditions": KnowledgeMetadata(
        title="Data Plan Terms & Conditions",
        doc_id="AUR-PLN-003",
        version="3.1",
        last_updated="June 2026",
        department="Legal & Compliance",
        category="mobile",
        sections=LONG_DOC_SECTIONS,
        brief=(
            "Official data/service terms. Cover: fair usage policy (personal "
            "non-commercial use, no reselling, no tethering beyond allowance, "
            "network management rights), speed & throttling matrix (128kbps "
            "Essential, 256kbps Standard, 512kbps Premium/Unlimited, 64kbps "
            "excess tethering, 1Mbps Business after 200GB, reduced speeds on "
            "international roaming), data add-ons catalog (1GB/$10, 5GB/$35, "
            "International Roaming Pass $15/day, Tethering Boost 10GB/$12, no "
            "carryover, billed next invoice, purchase channels), roaming data "
            "terms (180+ countries, disabled by default, enable via account "
            "settings), bill optimization guidance (lower tier if 60-day "
            "average <60%, autopay $5 discount, Family consolidation, Wi-Fi "
            "calling, remove add-ons), compliance notes (30-day notice for "
            "changes, FCC network management disclosure, termination without "
            "penalty on material changes), dispute resolution (30-day "
            "complaint window, 5-business-day investigation, credits for "
            "verified issues, FCC escalation after 60 days), and FAQs."
        ),
    ),
    "device_upgrade_guidelines": KnowledgeMetadata(
        title="Device Upgrade Guidelines",
        doc_id="AUR-DEV-001",
        version="2.0",
        last_updated="August 2026",
        department="Device Finance",
        category="mobile",
        brief=(
            "Rules for moving to a newer handset. Cover: eligibility (device on "
            "account 12+ months or 50% of installment term, max 2 unpaid "
            "installments, Active account), device financing limits table by "
            "credit tier (Tier A excellent 4 devices/$200 total, Tier B good "
            "3/$150, Tier C fair 2/$100), early-upgrade options table "
            "(12+ months standard trade-in, damaged = protection claim, "
            "lost/stolen = protection payout, <12 months = pay remaining "
            "balance), available device table with 24-month installments "
            "(iPhone 16 $899/$37.46, iPhone 16 Pro $1199/$49.96, Galaxy S25 "
            "$899, S25 Ultra $1299/$54.12, Pixel 9 $799/$33.29, Pixel 9 Pro "
            "$999/$41.63, OnePlus 12 $699/$29.13, Edge 50 $599/$24.96), 0% APR "
            "on Premium/Unlimited/Business vs 6.99% on Essential/Standard, "
            "down payment for Tier C, trade-in value ranges by category "
            "(flagship 40-60%, mid-range 25-40%, budget 15-25%, damaged "
            "10-30%), step-by-step upgrade process (8 steps), device "
            "protection transfer with no coverage gap, promo credit forfeiture "
            "on early payoff, and FAQs."
        ),
    ),
    "device_trade_in_process": KnowledgeMetadata(
        title="Device Trade-In Process",
        doc_id="AUR-DEV-002",
        version="2.3",
        last_updated="July 2026",
        department="Device Finance",
        category="mobile",
        brief=(
            "End-to-end trade-in process. Cover: eligibility (owned device, "
            "powers on and holds charge, Active account, not lost/stolen), "
            "valuation factors table (model, age depreciation 12-15%/year, "
            "screen cracks -30-50%, battery <80% -10-20%, activation lock must "
            "be removed, water damage -40-60%, frame damage -15-30%, "
            "accessories +$10-20, jailbroken/rooted -20%), valuation tiers A-F "
            "(Like New/Good/Fair/Poor/Broken/Non-functional), step-by-step "
            "trade-in flow (device diagnostics, instant quote, credit at point "
            "of sale, collection or prepaid label 7-day window, refurbishment "
            "inspection, credit finalized or difference billed), promotional "
            "stacking table (trade-in + PROMO-0003 $200 bonus yes, + plan promo "
            "yes, + two device promos no, + cash discount yes), device "
            "disposition (tiers A-C refurbished and resold, D-E refurbished or "
            "recycled, F recycled; data wiped per NIST 800-88), quote valid 14 "
            "days, and FAQs."
        ),
    ),
    "device_protection_policy": KnowledgeMetadata(
        title="Device Protection Policy",
        doc_id="AUR-DEV-003",
        version="2.0",
        last_updated="July 2026",
        department="Device Services",
        category="mobile",
        brief=(
            "Device protection plan catalog. Cover: coverage tiers (Tier 1 "
            "Screen Repair $5/mo $29 deductible, 1 screen per 12 months; Tier 2 "
            "Full Protection $12/mo $99 up to $1500 value; Tier 3 Loss & Theft "
            "$16/mo $199, replacement in 1-3 business days; Tier 4 Premium "
            "Care $22/mo $0 first screen, accessories to $200), claim process "
            "steps (report via app/website/store, verify tier, quote and "
            "collect deductible, authorize within 24 hours, ship in 1-3 days, "
            "14-day return of damaged device, close), claim limits table (Tier "
            "1 two screens, Tier 2 two per 12 months, Tier 3 two, Tier 4 "
            "three), deductible summary matrix (screen/accidental/loss&theft), "
            "activation and cancellation (add within 30 days of purchase, "
            "removal end of cycle, no prorated refund), extended warranty "
            "(+12 months on Tier 2+, mechanical breakdown only, no deductible), "
            "exclusions (cosmetic wear, retroactive coverage, pre-existing "
            "damage, activation-lock cases, loss without police report within "
            "7 days, devices not owned by account holder), refurbished "
            "replacement with 12-month warranty, and FAQs."
        ),
    ),
    # -------------------------------------------------------------------------
    # roaming/  (Carrier Services)
    # -------------------------------------------------------------------------
    "roaming-policy": KnowledgeMetadata(
        title="Roaming Policy",
        doc_id="AUR-ROM-001",
        version="1.3",
        last_updated="July 2026",
        department="Carrier Services",
        category="roaming",
        brief=(
            "General roaming rules on home and partner networks. Cover: "
            "definition of domestic roaming (rural partner coverage at no extra "
            "charge) vs international roaming, automatic network selection, "
            "domestic partner data fair-use cap of 50 GB per month then "
            "deprioritization, Canada and Mexico roaming included on Premium, "
            "Family, Unlimited, and Business plans, Wi-Fi calling available "
            "while roaming, 911/112 emergency calls always available, "
            "deprioritization on crowded partner networks, roaming usage meter "
            "notifications at 50/80/100%, and FAQs."
        ),
    ),
    "international-roaming-policy": KnowledgeMetadata(
        title="International Roaming Policy",
        doc_id="AUR-ROM-002",
        version="1.2",
        last_updated="August 2026",
        department="Carrier Services",
        category="roaming",
        brief=(
            "International roaming in 180+ countries. Cover: roaming passes "
            "table (Day $15/day 500 MB, Weekly $50/week 3 GB, Monthly "
            "$120/month 10 GB with US calling, Cruise $10/day 200 MB), "
            "pay-per-use rates without a pass ($2/MB data, $1.50/min calls "
            "received, $2.00/min made, $0.50 SMS sent, free SMS received, "
            "MMS $1.00), coverage regions table (North America, Europe 35+, "
            "Asia-Pacific 25+, Latin America 20+, Africa 15+, Middle East "
            "10+), activation steps (disabled by default, enable via "
            "app/web/phone 1-833-AURORA-INTL), data management while roaming "
            "(notifications at 50/80/100%, auto-purchase of an extra day pass, "
            "data saver mode, roaming limits in app), troubleshooting table "
            "(no service, cannot call, slow data, unexpected charges), and "
            "FAQs."
        ),
    ),
    "international_roaming_policy": KnowledgeMetadata(
        title="International Roaming Policy",
        doc_id="AUR-SRV-004",
        version="1.2",
        last_updated="August 2026",
        department="Carrier Services",
        category="roaming",
        brief=(
            "International roaming in 180+ countries (regional partner "
            "network). Cover: roaming passes table (Day $15/day 500 MB "
            "high-speed, Weekly $50/week 3 GB, Monthly $120/month 10 GB with "
            "unlimited in-country + US calls, Cruise $10/day 200 MB), "
            "pay-per-use rates without a pass ($2/MB data, $1.50/min calls "
            "received, $2.00/min made, $0.50 SMS, free SMS received, MMS "
            "$1.00), coverage regions table with network partners (North "
            "America Rogers/Telcel/Bell, Europe Vodafone/Orange/Deutsche "
            "Telekom, Asia-Pacific SoftBank/Singtel/Optus, Latin America Claro/"
            "Entel/Movistar, Africa MTN/Vodacom/Safaricom, Middle East Etisalat/"
            "STC/Zain), roaming activation (disabled by default, enable via "
            "app, portal, or 1-833-AURORA-INTL, instant no reboot), data "
            "management (50/80/100% notifications, auto-purchase of extra day "
            "pass, data roaming limits, data saver mode), troubleshooting "
            "(airplane mode 5 minutes, verify pass active, congestion), and "
            "FAQs."
        ),
    ),
    # -------------------------------------------------------------------------
    # customer/  (Customer Operations / Retail Operations / Marketing)
    # -------------------------------------------------------------------------
    "customer-verification-policy": KnowledgeMetadata(
        title="Customer Verification Policy",
        doc_id="AUR-CUS-001",
        version="2.0",
        last_updated="July 2026",
        department="Customer Operations",
        category="customer",
        brief=(
            "Verify customer identity before account actions. Cover: when "
            "verification is required (plan changes, device finance, device "
            "pickup, data requests, password reset, transferring service, "
            "unblocking lines), verification methods by channel table "
            "(in-store: two government IDs or biometric; phone: security PIN "
            "plus two security questions; online/app: one-time passcode via "
            "SMS; account holder only), exceptions for verified employees and "
            "authorized users, lockout after 3 failed attempts (30 minutes), "
            "minors on a family account handled only with the primary account "
            "holder, verification events logged and retained, suspected-fraud "
            "escalation, and FAQs."
        ),
    ),
    "complaint-handling-policy": KnowledgeMetadata(
        title="Complaint Handling Policy",
        doc_id="AUR-CUS-002",
        version="1.5",
        last_updated="August 2026",
        department="Customer Operations",
        category="customer",
        sections=LONG_DOC_SECTIONS,
        brief=(
            (
                "End-to-end complaint process. Cover: complaint channels (in-store, "
                "phone, chat, email, app, social media), categorization by type "
                "(billing, service, network, device) and priority (standard 48-hour "
                "first response, urgent 24 hours, critical same-day), complaint "
                "lifecycle (acknowledge, investigate, resolve, close with customer)"
            ),
            (
                "resolution targets per category table (billing 5 business days, "
                "network 24 hours for verified outage, device 7 business days), "
                "escalation ladder (frontline to supervisor to specialist team to "
                "ombudsman), escalation to CFPB/FCC/state regulator after 8 weeks "
                "unresolved, goodwill credit compensation policy, all complaints "
                "logged with a case number and SLA, monthly complaint analytics "
                "and reporting, and FAQs."
            ),
        ),
    ),
    "new_line_activation_process": KnowledgeMetadata(
        title="New Line Activation Process",
        doc_id="AUR-SRV-002",
        version="2.0",
        last_updated="July 2026",
        department="Retail Operations",
        category="customer",
        brief=(
            "End-to-end new line activation. Cover: pre-approval steps "
            "(identity + address proof, credit check if financing, KYC "
            "consent, plan/device selection, terms acceptance, activation "
            "fee), identity verification table (passport/driver license/"
            "national ID/military ID current; utility bill/bank statement/"
            "lease within 90 days; in-store biometric optional; online video "
            "verification within 1 hour), credit check table (soft pull BYOD "
            "no score impact, hard pull financed, none prepaid; valid 30 days; "
            "deposits $100-$500), SIM/eSIM provisioning (physical SIM instant "
            "in-store or shipped 2 business days; eSIM QR in minutes, "
            "compatible devices iPhone XS+/Galaxy S20+/Pixel 3+, dual-SIM; "
            "remote provisioning via app), activation flow (account created, "
            "SIM provisioned, welcome SMS in 2 minutes, welcome email, "
            "prorated first bill, 14-day return window), activation fees table "
            "(Essential/Standard $35 with waivers, Premium+) $0), first-bill "
            "expectations (prorated + full-month charges, taxes, activation "
            "fee, device installment, protection, promo credits), BYOD "
            "(unlocked, band compatible, IMEI check, $50 credit), and FAQs."
        ),
    ),
    "port_in_policy": KnowledgeMetadata(
        title="Port-In Policy",
        doc_id="AUR-SRV-001",
        version="2.5",
        last_updated="August 2026",
        department="Carrier Services",
        category="customer",
        brief=(
            "Number porting from other carriers. Cover: eligibility (active "
            "number in good standing, TPIN + account number required, not "
            "mid-port or suspended, no pending device obligations), required "
            "information table (phone number, losing-carrier account number, "
            "transfer PIN, exact name and billing/service address match), "
            "porting timelines (same region 2-4 hours, cross-region 24-48 "
            "hours, corporate/business 3-5 business days, prepaid-to-postpaid "
            "24-48 hours, US numbers only, international not supported), "
            "common failure reasons and resolutions table (wrong TPIN, "
            "incorrect account number, name/address mismatch, suspended line, "
            "pending device balance, already mid-port, losing carrier "
            "blocking), step-by-step port process, zero-day trouble resolution "
            "via the Port Desk chat (case number, 24-hour investigation, "
            "callback, escalation to carrier relations), partial port "
            "line-by-line, brief service interruption during transfer, and "
            "FAQs."
        ),
    ),
    "promotions_eligibility_terms": KnowledgeMetadata(
        title="Promotions & Offer Eligibility Terms",
        doc_id="AUR-PRO-001",
        version="2.0",
        last_updated="August 2026",
        department="Marketing Operations",
        category="customer",
        brief=(
            "Promotions and offer eligibility. Cover: offer catalog table "
            "(PROMO-0001 Premium Upgrade $10/mo off 12 mths, PROMO-0002 Family "
            "Bundle $15/mo off, PROMO-0003 Device Trade-In Bonus $200, "
            "PROMO-0004 Premium + Pixel Bundle $150 off, PROMO-0005 Win-Back "
            "Unlimited $75/mo 6 mths, PROMO-0006 Referral $50 credit, "
            "PROMO-0007 Senior Plan $25/mo 12 mths, PROMO-0008 Holiday Bundle "
            "Family + 2 devices $300 off), eligibility by account status table "
            "(Active, Prospect, Delinquent win-back only, Senior 65+), offer "
            "matching rules (max 2 offers per interaction, bundles cannot "
            "stack, win-back exclusive to delinquent, referral needs valid "
            "code), stacking rules table (plan + trade-in yes, plan + bundle "
            "no, two plan discounts no, win-back exclusive, referral + plan "
            "yes, referral + device yes, two device promos no, bundle + "
            "referral no), offer duration and expiry (plan discounts 12 "
            "months, device credits instant, bundles commitment-length, "
            "referral 30 days, win-back 6 months; 30-day expiry notice, no "
            "reactivation), promotional terms (availability, non-transferable, "
            "no cash value, fraud review, no discount on taxes/fees), customer "
            "communication (SMS/email/app/in-store, opt-out), and FAQs."
        ),
    ),
    "loyalty_rewards_program": KnowledgeMetadata(
        title="Loyalty & Rewards Program",
        doc_id="AUR-PRO-002",
        version="1.0",
        last_updated="August 2026",
        department="Marketing Operations",
        category="customer",
        brief=(
            "Aurora Rewards loyalty program. Cover: membership tiers table "
            "(Silver auto-enrolled 1pt/$1, Gold 5,000 pts 1.5x + priority "
            "support + early deal access, Platinum 15,000 pts 2x + one free "
            "device upgrade/year + concierge, Diamond 30,000 pts 2.5x + "
            "exclusive events + annual gift), earning points table (1pt/$1 "
            "monthly service, 2pt/$1 device purchase, 1pt/$1 accessories, 500 "
            "referral, 200 on-time 12 months, 100 autopay, 50 survey, 200 "
            "birthday), redemption table (500 pts=$5 credit, 1000=$10, 2500 free "
            "accessory to $50, 5000=$100 device credit, 7500 free month of "
            "service, 15000 upgrade discount to $500, 10000 exclusive event), "
            "point expiration (24 months of account inactivity, reminders at 60 "
            "and 30 days, tier reset annually on 12-month rolling total), "
            "terms & conditions (no cash value, non-transferable, program "
            "modification rights, fraud suspension), and FAQs."
        ),
    ),
    # -------------------------------------------------------------------------
    # compliance/  (Legal & Compliance / Network Operations)
    # -------------------------------------------------------------------------
    "kyc-policy": KnowledgeMetadata(
        title="KYC Policy",
        doc_id="AUR-LEG-010",
        version="2.0",
        last_updated="June 2026",
        department="Legal & Compliance",
        category="compliance",
        sections=LONG_DOC_SECTIONS,
        brief=(
            "Know Your Customer / Customer Identification Program for "
            "activations and device purchases. Cover: customer identification "
            "program (collect full name, date of birth, residential address, "
            "taxpayer ID; verify before new-line activation), acceptable "
            "documents table (passport, driver license, national ID, military "
            "ID; address proof utility bill/bank statement/lease within 90 "
            "days), verification methods (electronic database check, "
            "biometric, in-person), risk tiers with enhanced due diligence "
            "(standard, high-risk persons, politically exposed persons, large "
            "corporate accounts), sanctions and OFAC screening at activation, "
            "record retention 5 years after account close, consumer privacy "
            "limitations (CIP data used only for identification), no-service "
            "rule for unverifiable customers, suspected-fraud escalation to "
            "compliance, and FAQs."
        ),
    ),
    "data-privacy-policy": KnowledgeMetadata(
        title="Data Privacy Policy",
        doc_id="AUR-LEG-011",
        version="1.1",
        last_updated="August 2026",
        department="Legal & Compliance",
        category="compliance",
        sections=LONG_DOC_SECTIONS,
        brief=(
            "Customer privacy and data protection. Cover: data collected table "
            "(account information, payment information, device information, "
            "usage data, location data, app usage, support interactions), data "
            "usage principles (never sold, contractual sharing only, "
            "retention limits, deletion on request), customer rights table "
            "(access, correction, deletion, portability, marketing opt-out, "
            "restrict processing with app paths), third-party sharing table "
            "(payment processors PCI-DSS, network vendors anonymized, support "
            "platforms encrypted, regulators per law), data security (AES-256 "
            "at rest, TLS 1.3 in transit, MFA, audited employee access, "
            "penetration testing, 72-hour breach notification), data retention "
            "table (account +7 years, payment 7 years, call metadata 18 "
            "months, location 12 months, support 3 years, app usage 24 "
            "months), children's privacy (no under-13 data, parental consent "
            "for minors under 18), policy updates (30-day notice for material "
            "changes), and FAQs. Compliant with CCPA/GDPR."
        ),
    ),
    "privacy_data_protection_policy": KnowledgeMetadata(
        title="Privacy & Data Protection Policy",
        doc_id="AUR-LEG-001",
        version="1.0",
        last_updated="August 2026",
        department="Legal & Compliance",
        category="compliance",
        sections=LONG_DOC_SECTIONS,
        brief=(
            "Customer privacy and data protection (legal baseline). Cover: "
            "data collected table (account information, payment information, "
            "device information, usage data such as call logs and SMS "
            "metadata, location data with consent, app usage, support "
            "interactions), data usage principles (stated purposes only, never "
            "sold, contract-bound service providers, retention limits, "
            "deletion rights subject to legal retention), customer rights "
            "table (access, correction, deletion, portability, markting "
            "opt-out, restrict processing with app paths), third-party sharing "
            "and safeguards, data security (AES-256 at rest, TLS 1.3 in "
            "transit, multi-factor authentication, logged and monitored "
            "employee access, security audits, incident response with 72-hour "
            "breach notification), data retention table (account +7 years, "
            "payment records 7 years regulatory, call/SMS metadata 18 months, "
            "location 12 months, support interactions 3 years, app usage 24 "
            "months), children's privacy (no data under 13, parental consent "
            "for minors), policy updates (30-day notice for material "
            "changes), and FAQs."
        ),
    ),
    "network_service_level_agreement": KnowledgeMetadata(
        title="Network Service Level Agreement",
        doc_id="AUR-NET-001",
        version="1.1",
        last_updated="July 2026",
        department="Network Operations",
        category="compliance",
        sections=LONG_DOC_SECTIONS,
        brief=(
            "Network performance commitments and remedies. Cover: network "
            "uptime commitment table (99.9% monthly availability excluding "
            "maintenance, 99.5% voice call completion per 1000 attempts, 99.9% "
            "SMS delivery, 99.5% data session success, 98% population-weighted "
            "4G/5G coverage), scheduled maintenance windows (2:00-6:00 AM "
            "local, 72-hour SMS/email notice, max 4 windows/month, emergency "
            "maintenance exempt), outage response severity table (critical "
            "15-minute response/4-hour resolution major metro service loss; "
            "major 30-min/8-hr; moderate 1-hr/12-hr localized under 10,000 "
            "users; minor 4-hr/24-hr single-site), service credit table ($5 "
            "credit 2-4 hr, $10 4-8 hr, $20 8-24 hr, $50 + prorated daily plan "
            "charge 24+ hr; automatic for outages > 4 hours; one credit per "
            "event per line), coverage and speed guarantees (25 Mbps down / 10 "
            "Mbps up 4G, 100/20 Mbps 5G, latency under 50 ms 4G / 20 ms 5G, "
            "coverage map accuracy 95%), performance reporting (monthly "
            "reports, real-time outage map, quarterly regulatory data), how to "
            "report a network issue, and FAQs."
        ),
    ),
}


# =============================================================================
# 3. LLM DOCUMENT BODY GENERATION
# =============================================================================

SYSTEM_PROMPT = """\
You are Aurora Mobile's senior policy author, writing the Category B \
knowledge base used by retail staff and customer care across the US. You \
write precise, realistic telecom policies grounded in the exact figures and \
rules you are given, without inventing figures or limits beyond what the \
brief states.

Format rules:
- Output ONLY the document body in Markdown. No preamble, no title line \
starting with '#', and no "Document Information" block (the PDF template adds \
the canonical title and metadata header for you).
- Begin with a '## Overview' section that summarizes the document's purpose.
- Follow with logical '## Section' headings and short '### Subsection' headings.
- Use markdown tables when comparing structured data, and bullet or numbered \
lists for steps, criteria, and rules.
- Prefer concrete numbers (amounts, days, percentages, limits).
- End with a '## FAQs' section of 4-6 questions using this exact format on \
separate lines:
  **Q: <question>**
  **A: <answer>**
- You may end with italic call-to-action lines like a contact block.
- Write in US English. Avoid markdown that cannot render in a PDF: no images, \
no HTML, no fenced code blocks."""

OUTLINE_PROMPT = """\
You are Aurora Mobile's senior policy author planning a long, detailed \
document for the Category B knowledge base.

Produce a flat outline of the document described below: one heading per line, \
each starting with '## '. Include '## Overview' as the first heading and \
'## FAQs' as the last. The body should have enough sections to produce a \
document of approximately {target} pages when fully written, so use \
{n_sections} content sections between Overview and FAQs. Every topic in the "
brief must be covered by at least one section.

Output ONLY the outline headings, one per line, no preamble."""

SECTION_PROMPT = """\
You are Aurora Mobile's senior policy author writing the Category B \
knowledge base. Write ONLY the Markdown content for the sections listed below.

Rules:
- Write each section in full detail, as complete paragraphs plus bullet or \
numbered lists and markdown tables wherever structured data appears.
- Start each section with its exact '## <heading>' line.
- Use '### ' for subsections if helpful.
- Use only the figures, amounts, and rules stated in the brief; do not invent "
other figures.
- No preamble, no closing remarks, no 'Document Information' block."""

FAQ_PROMPT = """\
You are Aurora Mobile's senior policy author. Write ONLY the final
'## FAQs' section for the document described below.

Rules:
- Output exactly 5-7 FAQ items, one per block, in this exact format:
  **Q: <question>**
  **A: <answer>**
- Answers must use only figures from the brief.
- After the FAQs, you may add two italic lines as a contact block,
  e.g. '*Contact Finance Operations:*' and '*Email: ...*'.
- No preamble."""


def build_user_prompt(meta: KnowledgeMetadata) -> str:
    return f"""\
Write the complete Markdown body for the document below.

DOCUMENT TITLE: {meta.title}
DOCUMENT ID: {meta.doc_id}
VERSION: {meta.version}
LAST UPDATED: {meta.last_updated}
DEPARTMENT: {meta.department}
COMPANY: Aurora Mobile

CONTENT BRIEF:
{meta.brief}"""


def build_client(settings: Settings) -> tuple[OpenAI, str]:
    """Build the OpenRouter client and chat model from pipeline settings.

    The model comes from ``Settings.openrouter_model`` (``OPENROUTER_MODEL`` in
    the environment or ``.env``), the same value the RAG generator uses.
    """
    if not settings.openrouter_model:
        raise ValueError("OPENROUTER_MODEL is not configured")
    if not settings.openrouter_api_key:
        logger.warning("OPENROUTER_API_KEY is not set; generation requests will fail")
    client = OpenAI(
        base_url=settings.openrouter_base_url,
        api_key=settings.openrouter_api_key or None,
    )
    return client, settings.openrouter_model


def _usage(response) -> dict:
    """Normalize a chat-completion usage payload to a ``{tokens: count}`` dict."""
    usage = getattr(response, "usage", None)
    if usage is None:
        return {}
    if isinstance(usage, dict):
        return {
            key: usage[key]
            for key in ("prompt_tokens", "completion_tokens", "total_tokens")
            if usage.get(key)
        }
    return {
        key: getattr(usage, key)
        for key in ("prompt_tokens", "completion_tokens", "total_tokens")
        if getattr(usage, key, None)
    }


def _extract_text(response) -> str:
    """Return the first completion's text, or ``""`` when it is absent."""
    choices = getattr(response, "choices", None)
    if not isinstance(choices, list) or not choices:
        return ""
    message = getattr(choices[0], "message", None)
    if isinstance(message, dict):
        content = message.get("content")
    else:
        content = getattr(message, "content", None) if message is not None else None
    return content if isinstance(content, str) else ""


def _llm_generate(
    client: OpenAI,
    model: str,
    system: str,
    user: str,
    *,
    max_tokens: int | None = None,
    retries: int = 2,
) -> tuple[str, dict]:
    """Call the chat model with transient-failure retries, returning (text, usage)."""
    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]
    last_exc: Exception | None = None
    for attempt in range(1, retries + 1):
        try:
            kwargs = {"max_tokens": max_tokens or BODY_MAX_TOKENS}
            response = client.chat.completions.create(model=model, messages=messages, **kwargs)
            return _extract_text(response), _usage(response)
        except Exception as exc:  # retry transient failures
            last_exc = exc
            logger.warning("LLM call failed (attempt %s/%s): %s", attempt, retries, exc)
    raise last_exc


def _parse_outline(outline_md: str) -> list[str]:
    """Extract '## ' section titles (optionally numbered) from an outline."""
    titles: list[str] = []
    for line in outline_md.splitlines():
        line = line.strip()
        m = re.search(r"#+\s+(.*?)\s*$", line)
        if not m:
            continue
        title = m.group(1).strip().strip("*").strip()
        if title and title not in titles:
            titles.append(title)
    return titles


def _generate_long_doc(
    client: OpenAI, model: str, meta: KnowledgeMetadata, target_sections: int
) -> tuple[str, dict]:
    """Generate a document section-by-section so it exceeds 10 pages."""
    outline_prompt = OUTLINE_PROMPT.format(
        target=max(11, target_sections * 3 // 4), n_sections=target_sections
    )
    outline_user = build_user_prompt(meta)
    outline_md, _ = _llm_generate(
        client, model, outline_prompt, outline_user, max_tokens=OUTLINE_MAX_TOKENS
    )
    logger.info("%s outline: %d sections", meta.doc_id, len(_parse_outline(outline_md)))

    sections = _parse_outline(outline_md)
    # Guarantee the standard opening and closing sections.
    if not sections or sections[0].lower() != "overview":
        sections.insert(0, "Overview")
    if not sections or sections[-1].lower() != "faqs":
        sections.append("FAQs")

    body_parts: list[str] = []
    total_usage: dict = {}
    generated_sections = 0

    content_sections = [s for s in sections if not s.lower().startswith("faq")]
    for start in range(0, len(content_sections), SECTION_BATCH):
        batch = content_sections[start : start + SECTION_BATCH]
        section_lines = "\n".join(f"## {s}" for s in batch)
        user = (
            f"DOCUMENT TITLE: {meta.title}\nDOCUMENT ID: {meta.doc_id}\n"
            f"VERSION: {meta.version}\nLAST UPDATED: {meta.last_updated}\n"
            f"DEPARTMENT: {meta.department}\nCOMPANY: Aurora Mobile\n\n"
            f"CONTENT BRIEF:\n{meta.brief}\n\n"
            f"WRITE THESE SECTIONS:\n{section_lines}"
        )
        part, usage = _llm_generate(
            client, model, SECTION_PROMPT, user, max_tokens=SECTION_MAX_TOKENS
        )
        part = part.strip()
        if part:
            body_parts.append(part)
            generated_sections += len(batch)
        for key in ("prompt_tokens", "completion_tokens", "total_tokens"):
            if usage.get(key):
                total_usage[key] = total_usage.get(key, 0) + usage[key]

    faq_user = (
        f"DOCUMENT TITLE: {meta.title}\nDOCUMENT ID: {meta.doc_id}\n"
        f"VERSION: {meta.version}\nDEPARTMENT: {meta.department}\n"
        f"COMPANY: Aurora Mobile\n\nCONTENT BRIEF:\n{meta.brief}"
    )
    faq, usage = _llm_generate(client, model, FAQ_PROMPT, faq_user, max_tokens=FAQ_MAX_TOKENS)
    faq = faq.strip()
    if faq:
        body_parts.append(faq)
    for key in ("prompt_tokens", "completion_tokens", "total_tokens"):
        if usage.get(key):
            total_usage[key] = total_usage.get(key, 0) + usage[key]

    logger.info(
        "%s generated in %d section call(s) (%d sections, tokens: prompt=%s "
        "completion=%s total=%s)",
        meta.doc_id,
        len(content_sections) // SECTION_BATCH + 1,
        generated_sections,
        total_usage.get("prompt_tokens"),
        total_usage.get("completion_tokens"),
        total_usage.get("total_tokens"),
    )
    return "\n\n".join(body_parts), total_usage


def generate_body(client: OpenAI, model: str, meta: KnowledgeMetadata) -> tuple[str, dict]:
    """Generate the markdown body for a document via the configured LLM."""
    if meta.sections:
        return _generate_long_doc(client, model, meta, meta.sections)

    body, usage = _llm_generate(client, model, SYSTEM_PROMPT, build_user_prompt(meta))
    logger.info(
        "%s generated (tokens: prompt=%s completion=%s total=%s)",
        meta.doc_id,
        usage.get("prompt_tokens"),
        usage.get("completion_tokens"),
        usage.get("total_tokens"),
    )
    body = body.strip()
    if not body:
        raise RuntimeError(f"LLM returned an empty body for {meta.doc_id}")
    return body, usage


# =============================================================================
# 4. MARKDOWN -> REPORTLAB FLOWABLES
# =============================================================================

# Aurora Mobile brand palette
NAVY = colors.HexColor("#0B2A4A")
TEAL = colors.HexColor("#0E7C8A")
INK = colors.HexColor("#1F2933")
MUTED = colors.HexColor("#5B6770")
LIGHT = colors.HexColor("#F2F4F7")
BORDER = colors.HexColor("#C7CFD6")


def _escape_xml(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _inline(text: str) -> str:
    """Escape XML and convert markdown inline markup to ReportLab XML tags."""
    text = _escape_xml(text)
    codes: list[str] = []

    def _stash_code(m: "re.Match") -> str:
        codes.append(f'<font face="Courier" size="8.5" color="#333333">{m.group(1)}</font>')
        return f"\x00{len(codes) - 1}\x00"

    text = re.sub(r"`([^`]+)`", _stash_code, text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<i>\1</i>", text)
    for i, c in enumerate(codes):
        text = text.replace(f"\x00{i}\x00", c)
    return text


_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
_TABLE_ROW_RE = re.compile(r"^\s*\|")
_SEP_ROW_RE = re.compile(r"^\s*\|[\s:|-]+\|\s*$")
_BULLET_RE = re.compile(r"^([ \t]*)[-*+]\s+(.*)$")
_NUMBERED_RE = re.compile(r"^([ \t]*)(\d+)[.)]\s+(.*)$")
_QUOTE_RE = re.compile(r"^>\s?(.*)$")
_HR_RE = re.compile(r"^\s*(?:-{3,}|\*{3,}|_{3,})\s*$")

Block = tuple[str, str | list[list[str]] | tuple[int, str, str] | tuple[int, str]]


def _parse_markdown(body_md: str) -> list[Block]:
    """Split markdown body into (kind, payload) blocks.

    Kinds: h2 / h3 / h4 / para / bullets / numbered / table / quote / hr.
    """
    blocks: list[Block] = []
    for raw in body_md.splitlines():
        line = raw.rstrip()

        if _SEP_ROW_RE.match(line):
            continue

        head = _HEADING_RE.match(line)
        if head:
            level = len(head.group(1))
            kind = {2: "h2", 3: "h3", 4: "h4"}.get(level, "h2")
            blocks.append((kind, head.group(2).strip()))
            continue

        if _HR_RE.match(line):
            blocks.append(("hr", ""))
            continue

        match = _QUOTE_RE.match(line)
        if match:
            blocks.append(("quote", match.group(1).strip()))
            continue

        if _TABLE_ROW_RE.match(line):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if blocks and blocks[-1][0] == "table":
                blocks[-1][1].append(cells)  # type: ignore[arg-type]
            else:
                blocks.append(("table", [cells]))
            continue

        match = _NUMBERED_RE.match(line)
        if match:
            indent = len(match.group(1))
            blocks.append(("numbered", (indent, match.group(2), match.group(3).strip())))
            continue

        match = _BULLET_RE.match(line)
        if match:
            indent = len(match.group(1))
            blocks.append(("bullets", (indent, match.group(2).strip())))
            continue

        if not line.strip():
            continue

        blocks.append(("para", line.strip()))

    return blocks


# =============================================================================
# 5. PDF RENDERING
# =============================================================================

MARGIN = 0.72 * inch
AVAILABLE_WIDTH = letter[0] - 2 * MARGIN


def _build_styles() -> dict[str, ParagraphStyle]:
    return {
        "kicker": ParagraphStyle(
            "kicker",
            fontName="Helvetica-Bold",
            fontSize=9.5,
            textColor=TEAL,
            spaceAfter=4,
        ),
        "title": ParagraphStyle(
            "title",
            fontName="Helvetica-Bold",
            fontSize=24,
            leading=29,
            textColor=NAVY,
            spaceBefore=2,
            spaceAfter=6,
        ),
        "subtitle": ParagraphStyle(
            "subtitle",
            fontName="Helvetica",
            fontSize=10.5,
            leading=14,
            textColor=MUTED,
            spaceAfter=10,
        ),
        "h2": ParagraphStyle(
            "h2",
            fontName="Helvetica-Bold",
            fontSize=13.5,
            leading=17,
            textColor=NAVY,
            spaceBefore=14,
            spaceAfter=5,
        ),
        "h3": ParagraphStyle(
            "h3",
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=TEAL,
            spaceBefore=9,
            spaceAfter=3,
        ),
        "h4": ParagraphStyle(
            "h4",
            fontName="Helvetica-BoldOblique",
            fontSize=10.5,
            leading=13,
            textColor=INK,
            spaceBefore=8,
            spaceAfter=3,
        ),
        "body": ParagraphStyle(
            "body",
            fontName="Helvetica",
            fontSize=10,
            leading=14.5,
            textColor=INK,
            alignment=TA_JUSTIFY,
            spaceAfter=6,
        ),
        "bullet": ParagraphStyle(
            "bullet",
            fontName="Helvetica",
            fontSize=10,
            leading=14.5,
            textColor=INK,
            alignment=TA_LEFT,
            leftIndent=16,
            firstLineIndent=-8,
            spaceAfter=2,
        ),
        "number": ParagraphStyle(
            "number",
            fontName="Helvetica",
            fontSize=10,
            leading=14.5,
            textColor=INK,
            alignment=TA_LEFT,
            leftIndent=18,
            firstLineIndent=-10,
            spaceAfter=2,
        ),
        "quote": ParagraphStyle(
            "quote",
            fontName="Helvetica-Oblique",
            fontSize=9.5,
            leading=13,
            textColor=MUTED,
            leftIndent=14,
            rightIndent=6,
            spaceBefore=3,
            spaceAfter=6,
        ),
        "fq": ParagraphStyle(
            "fq",
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=14.5,
            textColor=NAVY,
            spaceBefore=8,
            spaceAfter=2,
        ),
        "fa": ParagraphStyle(
            "fa",
            fontName="Helvetica",
            fontSize=10,
            leading=14.5,
            textColor=INK,
            alignment=TA_JUSTIFY,
            leftIndent=12,
            spaceAfter=6,
        ),
        "table_cell": ParagraphStyle(
            "table_cell",
            fontName="Helvetica",
            fontSize=8.7,
            leading=11,
            textColor=INK,
        ),
        "table_head": ParagraphStyle(
            "table_head",
            fontName="Helvetica-Bold",
            fontSize=8.7,
            leading=11,
            textColor=colors.white,
        ),
    }


def _build_table(cells: list[list[str]], width: float, styles: dict) -> Table:
    styled = []
    for r, row in enumerate(cells):
        styled_row = []
        for cell in row:
            text = _inline(cell)
            style = styles["table_head"] if r == 0 else styles["table_cell"]
            styled_row.append(Paragraph(text, style))
        styled.append(styled_row)

    n_cols = max(len(r) for r in styled)
    col_width = width / max(n_cols, 1)
    col_widths = [col_width] * n_cols

    t = Table(styled, colWidths=col_widths, repeatRows=1)
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 3.5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    return t


def _body_to_flowables(body_md: str, styles: dict, width: float) -> list:
    flowables: list = []
    in_bullet_group = False
    in_number_group = False

    def _end_group() -> None:
        nonlocal in_bullet_group, in_number_group
        if in_bullet_group or in_number_group:
            flowables.append(Spacer(1, 4))
            in_bullet_group = False
            in_number_group = False

    for kind, payload in _parse_markdown(body_md):
        if kind in ("h2", "h3", "h4", "hr"):
            _end_group()
            if kind == "hr":
                flowables.append(
                    HRFlowable(
                        width="100%",
                        thickness=0.8,
                        color=BORDER,
                        spaceBefore=2,
                        spaceAfter=8,
                    )
                )
            else:
                flowables.append(Paragraph(_inline(payload), styles[kind]))
            continue

        if kind == "quote":
            _end_group()
            flowables.append(Paragraph(_inline(payload), styles["quote"]))
            continue

        if kind == "table":
            _end_group()
            flowables.append(_build_table(payload, width, styles))
            flowables.append(Spacer(1, 6))
            continue

        if kind == "bullets":
            indent, text = payload
            if not in_bullet_group:
                flowables.append(Spacer(1, 2))
                in_bullet_group = True
            indent_px = 9 * (indent // 2)
            style = ParagraphStyle(
                "bullet_lvl",
                parent=styles["bullet"],
                leftIndent=16 + indent_px,
                firstLineIndent=-9,
            )
            flowables.append(Paragraph(_inline(text), style, bulletText="\u2022"))
            continue

        if kind == "numbered":
            indent, num, text = payload
            if not in_number_group:
                flowables.append(Spacer(1, 2))
                in_number_group = True
            indent_px = 9 * (indent // 2)
            style = ParagraphStyle(
                "number_lvl",
                parent=styles["number"],
                leftIndent=18 + indent_px,
                firstLineIndent=-10,
            )
            flowables.append(Paragraph(_inline(text), style, bulletText=f"{num}."))
            continue

        # paragraph
        _end_group()
        if payload.startswith("**Q:"):
            flowables.append(Paragraph(_inline(payload), styles["fq"]))
        elif payload.startswith("**A:"):
            flowables.append(Paragraph(_inline(payload), styles["fa"]))
        else:
            flowables.append(Paragraph(_inline(payload), styles["body"]))

    _end_group()
    return flowables


def _make_info_table(meta: KnowledgeMetadata, styles: dict) -> Table:
    label = ParagraphStyle(
        "info_label",
        parent=styles["table_cell"],
        fontName="Helvetica-Bold",
        textColor=NAVY,
    )
    value = styles["table_cell"]
    rows = [
        [Paragraph("Document ID", label), Paragraph(meta.doc_id, value)],
        [Paragraph("Version", label), Paragraph(meta.version, value)],
        [Paragraph("Last Updated", label), Paragraph(meta.last_updated, value)],
        [Paragraph("Department", label), Paragraph(meta.department, value)],
        [Paragraph("Company", label), Paragraph("Aurora Mobile", value)],
        [
            Paragraph("Classification", label),
            Paragraph("Internal \u2014 Training & Reference", value),
        ],
    ]
    t = Table(rows, colWidths=[1.5 * inch, AVAILABLE_WIDTH - 1.5 * inch])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), LIGHT),
                ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    return t


def _pdf_page_count(path: Path) -> int:
    """Count pages in a rendered PDF by scanning its page objects."""
    data = path.read_bytes()
    return data.count(b"/Type /Page") - data.count(b"/Type /Pages")


def render_pdf(doc: KnowledgeDocument, out_path: Path) -> int:
    """Render one knowledge document to a branded Aurora Mobile PDF.

    Returns the number of pages in the rendered PDF.
    """
    meta = doc.metadata
    styles = _build_styles()

    def on_page(canvas, _doc) -> None:
        canvas.saveState()
        width, height = _doc.pagesize

        # Header band
        canvas.setFillColor(NAVY)
        canvas.setFont("Helvetica-Bold", 8)
        canvas.drawString(MARGIN, height - 0.55 * inch, "AURORA MOBILE")
        canvas.setFillColor(MUTED)
        canvas.setFont("Helvetica", 8)
        canvas.drawRightString(
            width - MARGIN,
            height - 0.55 * inch,
            f"{meta.doc_id}  \u00b7  v{meta.version}  \u00b7  {meta.title}",
        )
        canvas.setStrokeColor(BORDER)
        canvas.setLineWidth(0.7)
        canvas.line(MARGIN, height - 0.62 * inch, width - MARGIN, height - 0.62 * inch)

        # Footer band
        canvas.line(MARGIN, 0.5 * inch, width - MARGIN, 0.5 * inch)
        canvas.setFillColor(MUTED)
        canvas.setFont("Helvetica", 7.5)
        canvas.drawString(
            MARGIN,
            0.38 * inch,
            "Confidential \u2014 for internal training and reference only. \u00a9 2026 Aurora Mobile.",
        )
        canvas.drawRightString(
            width - MARGIN,
            0.38 * inch,
            f"Page {canvas.getPageNumber()}",
        )
        canvas.restoreState()

    story: list = []
    story.append(Spacer(1, 6))
    story.append(Paragraph("AURORA MOBILE  \u00b7  KNOWLEDGE BASE", styles["kicker"]))
    story.append(Paragraph(meta.title, styles["title"]))
    story.append(
        Paragraph(
            "Category B \u2014 Policy &amp; Process Knowledge Base",
            styles["subtitle"],
        )
    )
    story.append(_make_info_table(meta, styles))
    story.append(
        HRFlowable(
            width="100%",
            thickness=1.1,
            color=NAVY,
            spaceBefore=10,
            spaceAfter=2,
        )
    )
    story.extend(_body_to_flowables(doc.body_md, styles, AVAILABLE_WIDTH))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    document = SimpleDocTemplate(
        str(out_path),
        pagesize=letter,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=0.85 * inch,
        bottomMargin=0.75 * inch,
        title=f"{meta.title} \u2014 {meta.doc_id}",
        author="Aurora Mobile",
        subject="Category B knowledge base document",
    )
    document.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return _pdf_page_count(out_path)


# =============================================================================
# 6. CLI
# =============================================================================


def _parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="generate_sample_pdfs.py",
        description="Generate Aurora Mobile sample policy PDFs for the RAG "
        "pipeline using the chat model configured via .env "
        "(OPENROUTER_MODEL).",
    )
    parser.add_argument(
        "--out-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help="Output directory (default: data/raw)",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Generate only the first N documents (catalog order)",
    )
    parser.add_argument(
        "--only",
        action="append",
        default=None,
        metavar="NAME",
        help="Generate only matching document(s); may repeat. Matches name "
        "substring (e.g. --only roaming).",
    )
    parser.add_argument(
        "--keep-md",
        action="store_true",
        help="Also write the raw LLM markdown body next to each PDF.",
    )
    return parser.parse_args(argv)


def _resolve_targets(args: argparse.Namespace) -> list[tuple[str, KnowledgeMetadata]]:
    names = list(KB)
    if args.only:
        names = sorted({name for name in KB if any(token in name for token in args.only)})
        if not names:
            raise SystemExit(
                f"No document matched --only {args.only}. Available: " + ", ".join(sorted(KB))
            )
    if args.limit is not None:
        names = names[: args.limit]
    return [(name, KB[name]) for name in names]


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    targets = _resolve_targets(args)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    logger.info("Initializing OpenRouter client from pipeline settings (.env) ...")
    try:
        client, model = build_client(Settings())
    except (RuntimeError, ValueError) as exc:
        logger.error("Could not start LLM client: %s", exc)
        print(
            "Set OPENROUTER_MODEL and OPENROUTER_API_KEY in your environment "
            "or .env file before running this script."
        )
        return 1

    generated, failed = 0, 0
    long_count = 0
    for name, meta in targets:
        pdf_path = out_dir / meta.category / f"{name}.pdf"
        try:
            body, usage = generate_body(client, model, meta)
        except Exception as exc:  # keep going; report at the end
            logger.error("FAILED %s: %s", meta.doc_id, exc)
            failed += 1
            continue

        if usage.get("completion_tokens") == MAX_COMPLETION_TOKENS_TO_WARN:
            logger.warning(
                "%s hit the max_tokens ceiling (%d) — output may be "
                "truncated. Re-run with --only=%s to retry.",
                meta.doc_id,
                MAX_COMPLETION_TOKENS_TO_WARN,
                name,
            )

        doc = KnowledgeDocument(metadata=meta, body_md=body)
        pages = render_pdf(doc, pdf_path)
        if args.keep_md:
            (pdf_path.with_suffix(".md")).write_text(body + "\n", encoding="utf-8")
        print(f" - {pdf_path} ({pages} pages)")
        logger.info("%s rendered: %d pages", meta.doc_id, pages)
        generated += 1
        if pages > 10:
            long_count += 1

    print(
        f"\nSuccessfully generated knowledge base PDFs under "
        f"'{out_dir.resolve()}': {generated} document(s) generated, "
        f"{failed} failed ({long_count} exceed 10 pages)."
    )
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
